name: Build Binaries
on: [push]
jobs:
  Build-Binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.5'
      - run: mkdir dist
      - name: goSFDLSauger_linux_x64
        run: GOOS=linux GOARCH=amd64 go build -o dist/goSFDLSauger_linux_x64
      - name: goSFDLSauger_linux_arm
        run: GOOS=linux GOARCH=arm go build -o dist/goSFDLSauger_linux_arm
      - name: goSFDLSauger_linux_arm64
        run: GOOS=linux GOARCH=arm64 go build -o dist/goSFDLSauger_linux_arm64
      - name: goSFDLSauger_macOS_x64
        run: GOOS=darwin GOARCH=amd64 go build -o dist/goSFDLSauger_macOS_x64
      - name: goSFDLSauger.exe
        run: GOOS=windows GOARCH=amd64 go build -o dist/goSFDLSauger.exe
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/